# Generated by Django 4.0.2 on 2022-03-02 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('repository', models.CharField(max_length=256, verbose_name='Репозиторий')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст')),
                ('done', models.BooleanField(db_index=True, default=0, verbose_name='Выполнена')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.project', verbose_name='Проект')),
            ],
        ),
    ]
